name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Packages
      run: sudo apt install -y make pandoc pandoc-citeproc texlive texlive-bibtex-extra texlive-publishers texlive-lang-spanish
      
    - name: Tesis
      run: make tesis
      
    - name: Artículo
      run: make articulo
      
    - name: Proyecto
      run: make proyecto
